/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  jsonb,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => ({
    _orderIdx: index("users_sessions_order_idx").on(columns._order),
    _parentIDIdx: index("users_sessions_parent_id_idx").on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts").default("0"),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => ({
    users_updated_at_idx: index("users_updated_at_idx").on(columns.updatedAt),
    users_created_at_idx: index("users_created_at_idx").on(columns.createdAt),
    users_email_idx: uniqueIndex("users_email_idx").on(columns.email),
  }),
);

export const hero_content = pgTable(
  "hero_content",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    title: varchar("title").notNull(),
    subtitle: varchar("subtitle"),
    description: varchar("description"),
    github_url: varchar("github_url"),
    linkedin_url: varchar("linkedin_url"),
    resume_url: varchar("resume_url"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    hero_content_updated_at_idx: index("hero_content_updated_at_idx").on(
      columns.updatedAt,
    ),
    hero_content_created_at_idx: index("hero_content_created_at_idx").on(
      columns.createdAt,
    ),
  }),
);

export const experiences_achievements = pgTable(
  "experiences_achievements",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    achievement: varchar("achievement"),
  },
  (columns) => ({
    _orderIdx: index("experiences_achievements_order_idx").on(columns._order),
    _parentIDIdx: index("experiences_achievements_parent_id_idx").on(
      columns._parentID,
    ),
    _parentIDFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [experiences.id],
      name: "experiences_achievements_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const experiences_technologies = pgTable(
  "experiences_technologies",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    technology: varchar("technology"),
  },
  (columns) => ({
    _orderIdx: index("experiences_technologies_order_idx").on(columns._order),
    _parentIDIdx: index("experiences_technologies_parent_id_idx").on(
      columns._parentID,
    ),
    _parentIDFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [experiences.id],
      name: "experiences_technologies_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const experiences = pgTable(
  "experiences",
  {
    id: serial("id").primaryKey(),
    position: varchar("position").notNull(),
    company: varchar("company").notNull(),
    sort_order: numeric("sort_order").default("0"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    experiences_updated_at_idx: index("experiences_updated_at_idx").on(
      columns.updatedAt,
    ),
    experiences_created_at_idx: index("experiences_created_at_idx").on(
      columns.createdAt,
    ),
  }),
);

export const projects_technologies = pgTable(
  "projects_technologies",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    technology: varchar("technology"),
  },
  (columns) => ({
    _orderIdx: index("projects_technologies_order_idx").on(columns._order),
    _parentIDIdx: index("projects_technologies_parent_id_idx").on(
      columns._parentID,
    ),
    _parentIDFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [projects.id],
      name: "projects_technologies_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const projects = pgTable(
  "projects",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    description: varchar("description").notNull(),
    duration: varchar("duration"),
    github_url: varchar("github_url"),
    demo_url: varchar("demo_url"),
    image_url: varchar("image_url"),
    sort_order: numeric("sort_order").default("0"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    projects_updated_at_idx: index("projects_updated_at_idx").on(
      columns.updatedAt,
    ),
    projects_created_at_idx: index("projects_created_at_idx").on(
      columns.createdAt,
    ),
  }),
);

export const skills_skills = pgTable(
  "skills_skills",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    skill: varchar("skill"),
  },
  (columns) => ({
    _orderIdx: index("skills_skills_order_idx").on(columns._order),
    _parentIDIdx: index("skills_skills_parent_id_idx").on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [skills.id],
      name: "skills_skills_parent_id_fk",
    }).onDelete("cascade"),
  }),
);

export const skills = pgTable(
  "skills",
  {
    id: serial("id").primaryKey(),
    category: varchar("category").notNull(),
    sort_order: numeric("sort_order").default("0"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    skills_updated_at_idx: index("skills_updated_at_idx").on(columns.updatedAt),
    skills_created_at_idx: index("skills_created_at_idx").on(columns.createdAt),
  }),
);

export const contact_info = pgTable(
  "contact_info",
  {
    id: serial("id").primaryKey(),
    email: varchar("email").notNull(),
    phone: varchar("phone"),
    location: varchar("location"),
    github_url: varchar("github_url"),
    linkedin_url: varchar("linkedin_url"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    contact_info_updated_at_idx: index("contact_info_updated_at_idx").on(
      columns.updatedAt,
    ),
    contact_info_created_at_idx: index("contact_info_created_at_idx").on(
      columns.createdAt,
    ),
  }),
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_locked_documents_global_slug_idx: index(
      "payload_locked_documents_global_slug_idx",
    ).on(columns.globalSlug),
    payload_locked_documents_updated_at_idx: index(
      "payload_locked_documents_updated_at_idx",
    ).on(columns.updatedAt),
    payload_locked_documents_created_at_idx: index(
      "payload_locked_documents_created_at_idx",
    ).on(columns.createdAt),
  }),
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    "hero-contentID": integer("hero_content_id"),
    experiencesID: integer("experiences_id"),
    projectsID: integer("projects_id"),
    skillsID: integer("skills_id"),
    "contact-infoID": integer("contact_info_id"),
  },
  (columns) => ({
    order: index("payload_locked_documents_rels_order_idx").on(columns.order),
    parentIdx: index("payload_locked_documents_rels_parent_idx").on(
      columns.parent,
    ),
    pathIdx: index("payload_locked_documents_rels_path_idx").on(columns.path),
    payload_locked_documents_rels_users_id_idx: index(
      "payload_locked_documents_rels_users_id_idx",
    ).on(columns.usersID),
    payload_locked_documents_rels_hero_content_id_idx: index(
      "payload_locked_documents_rels_hero_content_id_idx",
    ).on(columns["hero-contentID"]),
    payload_locked_documents_rels_experiences_id_idx: index(
      "payload_locked_documents_rels_experiences_id_idx",
    ).on(columns.experiencesID),
    payload_locked_documents_rels_projects_id_idx: index(
      "payload_locked_documents_rels_projects_id_idx",
    ).on(columns.projectsID),
    payload_locked_documents_rels_skills_id_idx: index(
      "payload_locked_documents_rels_skills_id_idx",
    ).on(columns.skillsID),
    payload_locked_documents_rels_contact_info_id_idx: index(
      "payload_locked_documents_rels_contact_info_id_idx",
    ).on(columns["contact-infoID"]),
    parentFk: foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    usersIdFk: foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    "hero-contentIdFk": foreignKey({
      columns: [columns["hero-contentID"]],
      foreignColumns: [hero_content.id],
      name: "payload_locked_documents_rels_hero_content_fk",
    }).onDelete("cascade"),
    experiencesIdFk: foreignKey({
      columns: [columns["experiencesID"]],
      foreignColumns: [experiences.id],
      name: "payload_locked_documents_rels_experiences_fk",
    }).onDelete("cascade"),
    projectsIdFk: foreignKey({
      columns: [columns["projectsID"]],
      foreignColumns: [projects.id],
      name: "payload_locked_documents_rels_projects_fk",
    }).onDelete("cascade"),
    skillsIdFk: foreignKey({
      columns: [columns["skillsID"]],
      foreignColumns: [skills.id],
      name: "payload_locked_documents_rels_skills_fk",
    }).onDelete("cascade"),
    "contact-infoIdFk": foreignKey({
      columns: [columns["contact-infoID"]],
      foreignColumns: [contact_info.id],
      name: "payload_locked_documents_rels_contact_info_fk",
    }).onDelete("cascade"),
  }),
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_preferences_key_idx: index("payload_preferences_key_idx").on(
      columns.key,
    ),
    payload_preferences_updated_at_idx: index(
      "payload_preferences_updated_at_idx",
    ).on(columns.updatedAt),
    payload_preferences_created_at_idx: index(
      "payload_preferences_created_at_idx",
    ).on(columns.createdAt),
  }),
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => ({
    order: index("payload_preferences_rels_order_idx").on(columns.order),
    parentIdx: index("payload_preferences_rels_parent_idx").on(columns.parent),
    pathIdx: index("payload_preferences_rels_path_idx").on(columns.path),
    payload_preferences_rels_users_id_idx: index(
      "payload_preferences_rels_users_id_idx",
    ).on(columns.usersID),
    parentFk: foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    usersIdFk: foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  }),
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_migrations_updated_at_idx: index(
      "payload_migrations_updated_at_idx",
    ).on(columns.updatedAt),
    payload_migrations_created_at_idx: index(
      "payload_migrations_created_at_idx",
    ).on(columns.createdAt),
  }),
);

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_hero_content = relations(hero_content, () => ({}));
export const relations_experiences_achievements = relations(
  experiences_achievements,
  ({ one }) => ({
    _parentID: one(experiences, {
      fields: [experiences_achievements._parentID],
      references: [experiences.id],
      relationName: "achievements",
    }),
  }),
);
export const relations_experiences_technologies = relations(
  experiences_technologies,
  ({ one }) => ({
    _parentID: one(experiences, {
      fields: [experiences_technologies._parentID],
      references: [experiences.id],
      relationName: "technologies",
    }),
  }),
);
export const relations_experiences = relations(experiences, ({ many }) => ({
  achievements: many(experiences_achievements, {
    relationName: "achievements",
  }),
  technologies: many(experiences_technologies, {
    relationName: "technologies",
  }),
}));
export const relations_projects_technologies = relations(
  projects_technologies,
  ({ one }) => ({
    _parentID: one(projects, {
      fields: [projects_technologies._parentID],
      references: [projects.id],
      relationName: "technologies",
    }),
  }),
);
export const relations_projects = relations(projects, ({ many }) => ({
  technologies: many(projects_technologies, {
    relationName: "technologies",
  }),
}));
export const relations_skills_skills = relations(skills_skills, ({ one }) => ({
  _parentID: one(skills, {
    fields: [skills_skills._parentID],
    references: [skills.id],
    relationName: "skills",
  }),
}));
export const relations_skills = relations(skills, ({ many }) => ({
  skills: many(skills_skills, {
    relationName: "skills",
  }),
}));
export const relations_contact_info = relations(contact_info, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    "hero-contentID": one(hero_content, {
      fields: [payload_locked_documents_rels["hero-contentID"]],
      references: [hero_content.id],
      relationName: "hero-content",
    }),
    experiencesID: one(experiences, {
      fields: [payload_locked_documents_rels.experiencesID],
      references: [experiences.id],
      relationName: "experiences",
    }),
    projectsID: one(projects, {
      fields: [payload_locked_documents_rels.projectsID],
      references: [projects.id],
      relationName: "projects",
    }),
    skillsID: one(skills, {
      fields: [payload_locked_documents_rels.skillsID],
      references: [skills.id],
      relationName: "skills",
    }),
    "contact-infoID": one(contact_info, {
      fields: [payload_locked_documents_rels["contact-infoID"]],
      references: [contact_info.id],
      relationName: "contact-info",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);

type DatabaseSchema = {
  users_sessions: typeof users_sessions;
  users: typeof users;
  hero_content: typeof hero_content;
  experiences_achievements: typeof experiences_achievements;
  experiences_technologies: typeof experiences_technologies;
  experiences: typeof experiences;
  projects_technologies: typeof projects_technologies;
  projects: typeof projects;
  skills_skills: typeof skills_skills;
  skills: typeof skills;
  contact_info: typeof contact_info;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_hero_content: typeof relations_hero_content;
  relations_experiences_achievements: typeof relations_experiences_achievements;
  relations_experiences_technologies: typeof relations_experiences_technologies;
  relations_experiences: typeof relations_experiences;
  relations_projects_technologies: typeof relations_projects_technologies;
  relations_projects: typeof relations_projects;
  relations_skills_skills: typeof relations_skills_skills;
  relations_skills: typeof relations_skills;
  relations_contact_info: typeof relations_contact_info;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
