// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecjlvseneqrvbxdhlqxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjamx2c2VuZXFydmJ4ZGhscXhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNzkzNjQsImV4cCI6MjA2ODY1NTM2NH0.ssx3wrzjWb8bo05KC45VZFQ-7rz8Ym6H6xBe7Z344Gk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined, // Conditionally use localStorage
    persistSession: true,
    autoRefreshToken: true,
  }
});
